version: '3.8'

services:
  api:
    build: .
    container_name: health-assistant-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - DEVICE=cpu
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: health-assistant-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  default:
    name: health-assistant-network